
const CONTEXT_MENU_ITEMS_NAMESPACE = 'ContextMenu:items';
const CM_ALIAS = CONTEXT_MENU_ITEMS_NAMESPACE;
const CONTEXTMENU_ITEMS_NO_ITEMS = `${CM_ALIAS}.noItems`;
const CONTEXTMENU_ITEMS_ROW_ABOVE = `${CM_ALIAS}.insertRowAbove`;
const CONTEXTMENU_ITEMS_ROW_BELOW = `${CM_ALIAS}.insertRowBelow`;
const CONTEXTMENU_ITEMS_INSERT_LEFT = `${CM_ALIAS}.insertColumnOnTheLeft`;
const CONTEXTMENU_ITEMS_INSERT_RIGHT = `${CM_ALIAS}.insertColumnOnTheRight`;
const CONTEXTMENU_ITEMS_REMOVE_ROW = `${CM_ALIAS}.removeRow`;
const CONTEXTMENU_ITEMS_REMOVE_COLUMN = `${CM_ALIAS}.removeColumn`;
const CONTEXTMENU_ITEMS_UNDO = `${CM_ALIAS}.undo`;
const CONTEXTMENU_ITEMS_REDO = `${CM_ALIAS}.redo`;
const CONTEXTMENU_ITEMS_READ_ONLY = `${CM_ALIAS}.readOnly`;
const CONTEXTMENU_ITEMS_CLEAR_COLUMN = `${CM_ALIAS}.clearColumn`;
const CONTEXTMENU_ITEMS_COPY = `${CM_ALIAS}.copy`;
const CONTEXTMENU_ITEMS_COPY_WITH_COLUMN_HEADERS = `${CM_ALIAS}.copyWithHeaders`;
const CONTEXTMENU_ITEMS_COPY_WITH_COLUMN_GROUP_HEADERS = `${CM_ALIAS}.copyWithGroupHeaders`;
const CONTEXTMENU_ITEMS_COPY_COLUMN_HEADERS_ONLY = `${CM_ALIAS}.copyHeadersOnly`;
const CONTEXTMENU_ITEMS_CUT = `${CM_ALIAS}.cut`;
const CONTEXTMENU_ITEMS_FREEZE_COLUMN = `${CM_ALIAS}.freezeColumn`;
const CONTEXTMENU_ITEMS_UNFREEZE_COLUMN = `${CM_ALIAS}.unfreezeColumn`;
const CONTEXTMENU_ITEMS_MERGE_CELLS = `${CM_ALIAS}.mergeCells`;
const CONTEXTMENU_ITEMS_UNMERGE_CELLS = `${CM_ALIAS}.unmergeCells`;
const CONTEXTMENU_ITEMS_ADD_COMMENT = `${CM_ALIAS}.addComment`;
const CONTEXTMENU_ITEMS_EDIT_COMMENT = `${CM_ALIAS}.editComment`;
const CONTEXTMENU_ITEMS_REMOVE_COMMENT = `${CM_ALIAS}.removeComment`;
const CONTEXTMENU_ITEMS_READ_ONLY_COMMENT = `${CM_ALIAS}.readOnlyComment`;
const CONTEXTMENU_ITEMS_ALIGNMENT = `${CM_ALIAS}.align`;
const CONTEXTMENU_ITEMS_ALIGNMENT_LEFT = `${CM_ALIAS}.align.left`;
const CONTEXTMENU_ITEMS_ALIGNMENT_CENTER = `${CM_ALIAS}.align.center`;
const CONTEXTMENU_ITEMS_ALIGNMENT_RIGHT = `${CM_ALIAS}.align.right`;
const CONTEXTMENU_ITEMS_ALIGNMENT_JUSTIFY = `${CM_ALIAS}.align.justify`;
const CONTEXTMENU_ITEMS_ALIGNMENT_TOP = `${CM_ALIAS}.align.top`;
const CONTEXTMENU_ITEMS_ALIGNMENT_MIDDLE = `${CM_ALIAS}.align.middle`;
const CONTEXTMENU_ITEMS_ALIGNMENT_BOTTOM = `${CM_ALIAS}.align.bottom`;
const CONTEXTMENU_ITEMS_BORDERS = `${CM_ALIAS}.borders`;
const CONTEXTMENU_ITEMS_BORDERS_TOP = `${CM_ALIAS}.borders.top`;
const CONTEXTMENU_ITEMS_BORDERS_RIGHT = `${CM_ALIAS}.borders.right`;
const CONTEXTMENU_ITEMS_BORDERS_BOTTOM = `${CM_ALIAS}.borders.bottom`;
const CONTEXTMENU_ITEMS_BORDERS_LEFT = `${CM_ALIAS}.borders.left`;
const CONTEXTMENU_ITEMS_REMOVE_BORDERS = `${CM_ALIAS}.borders.remove`;
const CONTEXTMENU_ITEMS_NESTED_ROWS_INSERT_CHILD = `${CM_ALIAS}.nestedHeaders.insertChildRow`; // eslint-disable-line max-len
const CONTEXTMENU_ITEMS_NESTED_ROWS_DETACH_CHILD = `${CM_ALIAS}.nestedHeaders.detachFromParent`; // eslint-disable-line max-len
const CONTEXTMENU_ITEMS_HIDE_COLUMN = `${CM_ALIAS}.hideColumn`;
const CONTEXTMENU_ITEMS_SHOW_COLUMN = `${CM_ALIAS}.showColumn`;
const CONTEXTMENU_ITEMS_HIDE_ROW = `${CM_ALIAS}.hideRow`;
const CONTEXTMENU_ITEMS_SHOW_ROW = `${CM_ALIAS}.showRow`;
const FILTERS_NAMESPACE = 'Filters:';
const FILTERS_CONDITIONS_NAMESPACE = `${FILTERS_NAMESPACE}conditions`;
const FILTERS_CONDITIONS_NONE = `${FILTERS_CONDITIONS_NAMESPACE}.none`;
const FILTERS_CONDITIONS_EMPTY = `${FILTERS_CONDITIONS_NAMESPACE}.isEmpty`;
const FILTERS_CONDITIONS_NOT_EMPTY = `${FILTERS_CONDITIONS_NAMESPACE}.isNotEmpty`;
const FILTERS_CONDITIONS_EQUAL = `${FILTERS_CONDITIONS_NAMESPACE}.isEqualTo`;
const FILTERS_CONDITIONS_NOT_EQUAL = `${FILTERS_CONDITIONS_NAMESPACE}.isNotEqualTo`;
const FILTERS_CONDITIONS_BEGINS_WITH = `${FILTERS_CONDITIONS_NAMESPACE}.beginsWith`;
const FILTERS_CONDITIONS_ENDS_WITH = `${FILTERS_CONDITIONS_NAMESPACE}.endsWith`;
const FILTERS_CONDITIONS_CONTAINS = `${FILTERS_CONDITIONS_NAMESPACE}.contains`;
const FILTERS_CONDITIONS_NOT_CONTAIN = `${FILTERS_CONDITIONS_NAMESPACE}.doesNotContain`;
const FILTERS_CONDITIONS_BY_VALUE = `${FILTERS_CONDITIONS_NAMESPACE}.byValue`;
const FILTERS_CONDITIONS_GREATER_THAN = `${FILTERS_CONDITIONS_NAMESPACE}.greaterThan`;
const FILTERS_CONDITIONS_GREATER_THAN_OR_EQUAL = `${FILTERS_CONDITIONS_NAMESPACE}.greaterThanOrEqualTo`;
const FILTERS_CONDITIONS_LESS_THAN = `${FILTERS_CONDITIONS_NAMESPACE}.lessThan`;
const FILTERS_CONDITIONS_LESS_THAN_OR_EQUAL = `${FILTERS_CONDITIONS_NAMESPACE}.lessThanOrEqualTo`;
const FILTERS_CONDITIONS_BETWEEN = `${FILTERS_CONDITIONS_NAMESPACE}.isBetween`;
const FILTERS_CONDITIONS_NOT_BETWEEN = `${FILTERS_CONDITIONS_NAMESPACE}.isNotBetween`;
const FILTERS_CONDITIONS_AFTER = `${FILTERS_CONDITIONS_NAMESPACE}.after`;
const FILTERS_CONDITIONS_BEFORE = `${FILTERS_CONDITIONS_NAMESPACE}.before`;
const FILTERS_CONDITIONS_TODAY = `${FILTERS_CONDITIONS_NAMESPACE}.today`;
const FILTERS_CONDITIONS_TOMORROW = `${FILTERS_CONDITIONS_NAMESPACE}.tomorrow`;
const FILTERS_CONDITIONS_YESTERDAY = `${FILTERS_CONDITIONS_NAMESPACE}.yesterday`;
const FILTERS_DIVS_FILTER_BY_CONDITION = `${FILTERS_NAMESPACE}labels.filterByCondition`;
const FILTERS_DIVS_FILTER_BY_VALUE = `${FILTERS_NAMESPACE}labels.filterByValue`;
const FILTERS_LABELS_CONJUNCTION = `${FILTERS_NAMESPACE}labels.conjunction`;
const FILTERS_LABELS_DISJUNCTION = `${FILTERS_NAMESPACE}labels.disjunction`;
const FILTERS_VALUES_BLANK_CELLS = `${FILTERS_NAMESPACE}values.blankCells`;
const FILTERS_BUTTONS_SELECT_ALL = `${FILTERS_NAMESPACE}buttons.selectAll`;
const FILTERS_BUTTONS_CLEAR = `${FILTERS_NAMESPACE}buttons.clear`;
const FILTERS_BUTTONS_OK = `${FILTERS_NAMESPACE}buttons.ok`;
const FILTERS_BUTTONS_CANCEL = `${FILTERS_NAMESPACE}buttons.cancel`;
const FILTERS_BUTTONS_PLACEHOLDER_SEARCH = `${FILTERS_NAMESPACE}buttons.placeholder.search`;
const FILTERS_BUTTONS_PLACEHOLDER_VALUE = `${FILTERS_NAMESPACE}buttons.placeholder.value`;
const FILTERS_BUTTONS_PLACEHOLDER_SECOND_VALUE = `${FILTERS_NAMESPACE}buttons.placeholder.secondValue`;
const arAR = {
  languageCode: 'ar-AR',
  languageDirection: 'rtl',
  [CONTEXTMENU_ITEMS_NO_ITEMS]: 'لا توجد خيارات متوفرة',
  [CONTEXTMENU_ITEMS_ROW_ABOVE]: 'إدراج صف للأعلى',
  [CONTEXTMENU_ITEMS_ROW_BELOW]: 'إدراج صف للأسفل',
  [CONTEXTMENU_ITEMS_INSERT_LEFT]: 'إدراج عمود لليسار',
  [CONTEXTMENU_ITEMS_INSERT_RIGHT]: 'إدراج عمود لليمين',
  [CONTEXTMENU_ITEMS_REMOVE_ROW]: ['احدف الصف', 'احذف الصفوف'],
  [CONTEXTMENU_ITEMS_REMOVE_COLUMN]: ['احدف العمود', 'احدف الأعمدة'],
  [CONTEXTMENU_ITEMS_UNDO]: 'تراجع',
  [CONTEXTMENU_ITEMS_REDO]: 'إلغاء التراجع',
  [CONTEXTMENU_ITEMS_READ_ONLY]: 'للقراءة فقط',
  [CONTEXTMENU_ITEMS_CLEAR_COLUMN]: 'افرغ العمود',
  [CONTEXTMENU_ITEMS_ALIGNMENT]: 'المحاذاة',
  [CONTEXTMENU_ITEMS_ALIGNMENT_LEFT]: 'يسار',
  [CONTEXTMENU_ITEMS_ALIGNMENT_CENTER]: 'وسط',
  [CONTEXTMENU_ITEMS_ALIGNMENT_RIGHT]: 'يمين',
  [CONTEXTMENU_ITEMS_ALIGNMENT_JUSTIFY]: 'بالتساوي',
  [CONTEXTMENU_ITEMS_ALIGNMENT_TOP]: 'أعلى',
  [CONTEXTMENU_ITEMS_ALIGNMENT_MIDDLE]: 'متوسط',
  [CONTEXTMENU_ITEMS_ALIGNMENT_BOTTOM]: 'أسفل',
  [CONTEXTMENU_ITEMS_FREEZE_COLUMN]: 'تجميد العمود',
  [CONTEXTMENU_ITEMS_UNFREEZE_COLUMN]: 'إلغاء تجميد العمود',
  [CONTEXTMENU_ITEMS_BORDERS]: 'الحدود',
  [CONTEXTMENU_ITEMS_BORDERS_TOP]: 'أعلى',
  [CONTEXTMENU_ITEMS_BORDERS_RIGHT]: 'يمين',
  [CONTEXTMENU_ITEMS_BORDERS_BOTTOM]: 'أسفل',
  [CONTEXTMENU_ITEMS_BORDERS_LEFT]: 'يسار',
  [CONTEXTMENU_ITEMS_REMOVE_BORDERS]: 'أحذف الحد(ود)',
  [CONTEXTMENU_ITEMS_ADD_COMMENT]: 'أضف تعليقاً',
  [CONTEXTMENU_ITEMS_EDIT_COMMENT]: 'تعديل التعليق',
  [CONTEXTMENU_ITEMS_REMOVE_COMMENT]: 'احذف التعليق',
  [CONTEXTMENU_ITEMS_READ_ONLY_COMMENT]: 'تعليق للقراءة فقط',
  [CONTEXTMENU_ITEMS_MERGE_CELLS]: 'ادمج الخلايا',
  [CONTEXTMENU_ITEMS_UNMERGE_CELLS]: 'إلغاء دمج الخلايا',
  [CONTEXTMENU_ITEMS_COPY]: 'نسخ',
  [CONTEXTMENU_ITEMS_CUT]: 'قص',
  [CONTEXTMENU_ITEMS_NESTED_ROWS_INSERT_CHILD]: 'أدخل صفاً فرعياً',
  [CONTEXTMENU_ITEMS_NESTED_ROWS_DETACH_CHILD]: 'افصل عن الصف الأصلي',
  [CONTEXTMENU_ITEMS_HIDE_COLUMN]: ['إخفاء العمود', 'إخفاء الأعمدة'],
  [CONTEXTMENU_ITEMS_SHOW_COLUMN]: ['إظهار العمود', 'إظهار الأعمدة'],
  [CONTEXTMENU_ITEMS_HIDE_ROW]: ['إخفاء السطر', 'إخفاء السطور'],
  [CONTEXTMENU_ITEMS_SHOW_ROW]: ['إظهار السطر', 'إظهار السطور'],
  [FILTERS_CONDITIONS_NONE]: 'بلا',
  [FILTERS_CONDITIONS_EMPTY]: 'فارغ',
  [FILTERS_CONDITIONS_NOT_EMPTY]: 'غير فارغ',
  [FILTERS_CONDITIONS_EQUAL]: 'يساوي',
  [FILTERS_CONDITIONS_NOT_EQUAL]: 'لا يساوي',
  [FILTERS_CONDITIONS_BEGINS_WITH]: 'يبداً بـ',
  [FILTERS_CONDITIONS_ENDS_WITH]: 'ينتهي بـ',
  [FILTERS_CONDITIONS_CONTAINS]: 'يحتوي',
  [FILTERS_CONDITIONS_NOT_CONTAIN]: 'لا يحتوي',
  [FILTERS_CONDITIONS_GREATER_THAN]: 'أكبر من',
  [FILTERS_CONDITIONS_GREATER_THAN_OR_EQUAL]: 'أكبر أو يساوي',
  [FILTERS_CONDITIONS_LESS_THAN]: 'أصغر',
  [FILTERS_CONDITIONS_LESS_THAN_OR_EQUAL]: 'أصغر أو يساوي',
  [FILTERS_CONDITIONS_BETWEEN]: 'بين',
  [FILTERS_CONDITIONS_NOT_BETWEEN]: 'خارج المجال',
  [FILTERS_CONDITIONS_AFTER]: 'بعد',
  [FILTERS_CONDITIONS_BEFORE]: 'قبل',
  [FILTERS_CONDITIONS_TODAY]: 'اليوم',
  [FILTERS_CONDITIONS_TOMORROW]: 'غداً',
  [FILTERS_CONDITIONS_YESTERDAY]: 'البارحة',
  [FILTERS_VALUES_BLANK_CELLS]: 'خلايا فارغة',
  [FILTERS_DIVS_FILTER_BY_CONDITION]: 'تصفية حسب الشرط',
  [FILTERS_DIVS_FILTER_BY_VALUE]: 'تصفية حسب القيمة',
  [FILTERS_LABELS_CONJUNCTION]: 'و',
  [FILTERS_LABELS_DISJUNCTION]: 'أو',
  [FILTERS_BUTTONS_SELECT_ALL]: 'اختيار الكل',
  [FILTERS_BUTTONS_CLEAR]: 'إلغاء',
  [FILTERS_BUTTONS_OK]: 'موافق',
  [FILTERS_BUTTONS_CANCEL]: 'إلغاء',
  [FILTERS_BUTTONS_PLACEHOLDER_SEARCH]: 'البحث',
  [FILTERS_BUTTONS_PLACEHOLDER_VALUE]: 'القيمة',
  [FILTERS_BUTTONS_PLACEHOLDER_SECOND_VALUE]: 'القيمة الثانية',
  [CONTEXTMENU_ITEMS_COPY_WITH_COLUMN_HEADERS]: ['نسخ مع العنوان', 'نسخ مع العنوان'],
  [CONTEXTMENU_ITEMS_COPY_WITH_COLUMN_GROUP_HEADERS]: ['نسخ مع مجموعه العناوين', 'نسخ مع مجموعه العناوين'],
  [CONTEXTMENU_ITEMS_COPY_COLUMN_HEADERS_ONLY]: ['نسخ العنوان فقط', 'نسخ العنوان فقط'],
};
export default arAR;
